site_name: Demo Seite von Natalia
site_url: http://gbs.niederer.swiss/dta22/Natalia
theme:
  name: material
  palette:
    scheme: slate
    primary: purple
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
nav:
  - Home: index.md
  - Details: details.md
copyright: "Version: ${BUILD_VERSION}"
